# Generated by Django 2.2.2 on 2019-09-24 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vtuber',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('liver_name', models.CharField(max_length=100)),
                ('production', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='On_Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('live_title', models.CharField(max_length=100)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Vtuber')),
            ],
        ),
    ]
