# Generated by Django 2.2.4 on 2019-10-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190925_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('production', models.CharField(max_length=100)),
            ],
        ),
    ]
