# Generated by Django 2.2.2 on 2020-04-05 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_livelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledLive',
            fields=[
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Vtuber', unique=True)),
                ('start_time', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('live_url', models.CharField(max_length=100)),
            ],
        ),
    ]
