# Generated by Django 2.2.2 on 2020-09-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_vtuber_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vtuber',
            name='src',
        ),
        migrations.AddField(
            model_name='on_live',
            name='viewer',
            field=models.IntegerField(default=0),
        ),
    ]
