# Generated by Django 2.2.2 on 2020-12-26 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200922_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminds',
            fields=[
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Vtuber', unique=True)),
                ('start_datetime', models.CharField(max_length=100)),
                ('live_title', models.CharField(max_length=100)),
                ('live_url', models.CharField(max_length=100)),
                ('audience', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='on_live',
            name='viewer',
        ),
    ]
