# Generated by Django 2.2.4 on 2019-09-25 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='on_live',
            name='id',
        ),
        migrations.AlterField(
            model_name='on_live',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Vtuber'),
        ),
    ]
