# Generated by Django 2.2.2 on 2019-09-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190925_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='on_live',
            name='live_url',
            field=models.CharField(default='no url', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='on_live',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Vtuber', unique=True),
        ),
        migrations.AlterField(
            model_name='vtuber',
            name='uid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
